name: MePlugin
main: info.insomniax.shadoman75.bukkit.MePlugin
version: 0.0.1
depend: [Vault]
commands:
  me:
    description: shows something happening to the player
    usage: /me [message]
  meall:
    description: forces all players to do /me and your message
    usage: /meall [message]